[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via-ir = true
remappings = ["context-proxy/=../context-proxy/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
